feat: Added flyway script to create new tables
hmcts/rd-location-ref-api pull request #216
Opened 2021-04-27 13:03 UTC by SujeethKumarAri

JIRA link
https://tools.hmcts.net/jira/browse/RDCC-2719

Change description
Extended the LRD Database to create the new tables

Data Model can be found here - https://tools.hmcts.net/confluence/display/RTRD/Location+Reference+Data+-+Data+Model

Source to target mapping can be found here - https://tools.hmcts.net/confluence/display/RTRD/Location+Reference+Data+-+Source-to-Target+mapping
**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-04-27 14:31 UTC, shreedhar-hmcts approved these changes

2021-04-27 14:35 UTC, AdilOoze approved these changes

2021-04-27 14:39 UTC, abhijitdiwan approved these changes

2021-04-27 14:57 UTC, kavithagade12 requested changes

2021-04-27 14:57 UTC, kavithagade12 commented on src/integrationTest/resources/db/migration/V1_9__create_tables.sql
> +	court_location_code varchar(8) NOT NULL,
We do not have court location code at the moment. Please make it as nullable

2021-04-29 08:18 UTC, SujeethKumarAri commented
Closing as this being addressed already

2021-04-29 08:18 UTC, closed without merging