RDCC-2927: Insert data into HMCTS Services to court type mapping table
hmcts/rd-location-ref-api pull request #265
Opened 2021-06-28 12:51 UTC by ishratt

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-2927

### Change description ###
Adding data into static table ` court_type_service_assoc`

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-06-28 13:37 UTC, AdilOoze approved these changes

2021-06-28 13:39 UTC, SujeethKumarAri approved these changes

2021-06-28 15:52 UTC, abhijitdiwan requested changes
Have a look kube logs and see why this PR failed

2021-06-29 16:14 UTC, abhijitdiwan approved these changes

2021-06-29 16:30 UTC, merged